services:
  - type: web
    name: climate-risk-dashboard
    runtime: image
    image:
      buildPath: .
      dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5